### ISSUE TITLE
How can I make it work? I already installed, and I don't know what to do.

### ISSUE THREAD

**Issue by lioalde** [AsyJAIZ/Notification-Shade-Transparency#7]

**Comment by AsyJAIZ** [comment]
reboot the phone? provide the logs?

**Comment by AsyJAIZ** [comment]
it seems like you are new to modules.
if you install the module that involves a system app, you may be able to restart it from LSPosed itself, but for system services such as a “SystemUI“ or “Android Framework” the simplest way to restart those apps is to reboot the whole device, since those are the wrap of the whole interface.
also, if you’re thinking that some modules don’t work, don’t forget to look inside the logs inside LSPosed.

if my module produces “not found” exceptions, that may mean that you’re using some different user interface such as OneUI, MIUI, etc. those are **NOT supported.**
the only UI supported and confirmed to be compatible with this module is stock Android  UI (or the UI with minimal changes in the code) because it is open source and i use it on a daily basis.
